### ISSUE TITLE
增强：缓存对象必须实现Serializable接口，但是经常对象里面存在第三方lib对象的成员变量。就会序列化出错了。

### ISSUE THREAD

**Issue by caprice** [z-chu/RxCache#10]
缓存对象必须实现Serializable接口，但是经常对象里面存在第三方lib对象的成员变量其并没有实现Serializable, 就会序列化出错了。这个时候就需要先将整个对象转化成json-》String,然后缓存。取出来时也需要一序列的反向转化。是否考虑过支持这样的场景？

**Comment by z-chu** [comment]
这个已经有了啊，使用`.diskConverter(new GsonDiskConverter())`配置即可

**Comment by caprice** [comment]
确实有了，我代码拉下来，准备自己改写了。。。囧
