### ISSUE TITLE
[泛型擦除]有kotlin版本吗，kotlin可以解决泛型擦除的来着？

### ISSUE THREAD

**Issue by dyguests** [z-chu/RxCache#14]
如果有kotlin的话，就可以不要以下这一句代码了

new TypeToken<List<GankBean.ResultsBean>>() {}.getType()

:)

**Comment by z-chu** [comment]
暂时没有，我还没开始用kotlin，如果等我弄的话可能需要很久。如果可以，欢迎你PR!

**Comment by dyguests** [comment]
我暂时没有时间，总之关键代码就这一段：）

https://github.com/dyguests/RxCache/blob/master/library/src/main/java/com/fanhl/rxcache/RxCache.kt#L23-L26

**Comment by z-chu** [comment]
可以的 大兄弟
