### ISSUE TITLE
 配合retrofit使用时如何将url当作key使用啊

### ISSUE THREAD

**Issue by H-Sagiri** [z-chu/RxCache#15]

**Comment by z-chu** [comment]
。。把url作为key传入 - -！

**Comment by z-chu** [comment]
你可以尝试使用 key= 方法名+方法参数值

**Comment by H-Sagiri** [comment]
配合retrofit使用时url动态生成，不能直接使用这个吗？直接使用retrofit的url当做key,而且我也没有找到过期时间设置的方法，大佬可以加下这个功能吗？

**Comment by z-chu** [comment]
不能，这个库只做缓存这件事和retrofit没有任何关系。 过期时间设置后面我会考虑加一个新的缓存策略的

**Comment by H-Sagiri** [comment]
谢谢大佬，我会关注您的，感谢你您的回复
