### ISSUE TITLE
rxCache.load 和 rxCache.transformObservable的key转换规则不一致

### ISSUE THREAD

**Issue by skcks** [z-chu/RxCache#19]
如题，rxCache.load把参数key一次md5后作为缓存key，而rxCache.transformObservable却以参数key二次md5作为缓存key？？？为毛这样设计，求指教。

**Comment by z-chu** [comment]
你使用的是否是master分支的代码或者最新版本的代码？我记得v2是一致的，v1版本的可能我写错了

**Comment by skcks** [comment]
用的是   implementation 'com.zchu:rxcache:2.1.0'

**Comment by z-chu** [comment]
使用最新版2.3.0吧，那是一个老版本的bug

**Comment by skcks** [comment]
老哥你的包发在那个仓库了，怎么都下不到

**Comment by z-chu** [comment]
兄弟抱歉

**Comment by z-chu** [comment]
文档没写全，加上这个
```
allprojects {
    repositories {
         ...
        maven{url 'https://dl.bintray.com/zchu/maven/'}
        ...
    }
}
```
