### ISSUE TITLE
LruDiskCache出现问题

### ISSUE THREAD

**Issue by Deepblue1996** [z-chu/RxCache#33]
02-28 15:36:31.346 29465-30386/com.prohua.dovedemo E/[RxCache]: LruDiskCache.save(LruDiskCache.java:70)
                                                                	save:  value=com.prohua.dovedemo.bean.NetBase@2a2de86 , status=true

**Comment by Deepblue1996** [comment]
![image](https://user-images.githubusercontent.com/16926380/53549484-3ea63780-3b6f-11e9-864c-2a14552ffa37.png)

**Comment by z-chu** [comment]
上面的日志是成功保存到硬盘的日志 有什么问题吗

**Comment by Deepblue1996** [comment]
我还以为出问题了。。。
LruDiskCache.save(LruDiskCache.java:70) 日志是error类型
