### ISSUE TITLE
Jcenter 仓库地址已失效

### ISSUE THREAD

**Issue by iplanetcn** [z-chu/RxCache#44]
> Could not resolve all files for configuration ':tft:opsDebugRuntimeClasspath'.
   > Could not resolve com.zchu:rxcache:2.3.1.
     Required by:
         project :tft
      > Could not resolve com.zchu:rxcache:2.3.1.
         > Could not get resource 'https://dl.bintray.com/zchu/maven/com/zchu/rxcache/2.3.1/rxcache-2.3.1.pom'.
            > Could not GET 'https://dl.bintray.com/zchu/maven/com/zchu/rxcache/2.3.1/rxcache-2.3.1.pom'. Received status code 403 from server: Forbidden

请上传至其他可用的仓库

**Comment by z-chu** [comment]
项目已上传到 jitpack，README 已更新
