### ISSUE TITLE
2.3.3的库引用失败 

### ISSUE THREAD

**Issue by huangjie21** [z-chu/RxCache#45]
Unable to resolve dependency for ':app@chineseDebug/compileClasspath': Could not resolve com.github.z-chu.RxCache:rxcache:2.3.3.

是不是2.3.3 的版本 没有上传到jitpack
退到2.3.1 也不行。

原来使用的项目太旧，androidx 2.3.5的又用不了

**Comment by z-chu** [comment]
是的， 没有上传到 jitpack，建议你把最新的代码拉下来把 androidx 改为 support 库
