### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by findvoid** [z-chu/RxCache#5]
<img width="1591" alt="qq20170623-163935 2x" src="https://user-images.githubusercontent.com/13435914/27473686-90f8d49c-5832-11e7-95be-9801373230bc.png">

**Comment by findvoid** [comment]
RxJava1

**Comment by z-chu** [comment]
有在多个线程对一个ArrayList 进行操作吗？ 可以将你的调用代码贴出来吗

**Comment by findvoid** [comment]
我这里是有多个fragment,执行结束后分别调用.compose(DeepApp.getInstance().getRxCache()
                        .<OperateResult<T>>transformer(
                                defaultCacheKey()
                                , new TypeToken<OperateResult<T>>() {
                                }.getType()
                                , defaultCacheStrategy()))

**Comment by findvoid** [comment]
应该是多线程导致的,嵌套fragment

**Comment by findvoid** [comment]
使用版本com.zchu:rxcache:1.2.3

**Comment by z-chu** [comment]
是的，是个多线程同时操作ArrayList 导致的。你可以先将内存缓存大小设置为0，来暂时规避这个问题。我之后会解决这个问题的

**Comment by findvoid** [comment]
好的

**Comment by findvoid** [comment]
内存大小设为0还是会出现相同的问题

**Comment by findvoid** [comment]
.memoryMax(0)

**Comment by z-chu** [comment]
好吧，我晚上看一下。

**Comment by z-chu** [comment]
.<OperateResult>transformer(
defaultCacheKey()
, new TypeToken<OperateResult>() {
}.getType()
, defaultCacheStrategy()))

**Comment by findvoid** [comment]
好的  多谢了

**Comment by z-chu** [comment]
.<OperateResult>transformer(
defaultCacheKey()
, new TypeToken<OperateResult>() {
}.getType()
, defaultCacheStrategy()))

如果缓存不是list<T>这种带泛型的type，可以直接传class。还有最好不要用同一个key,估计同时对同一个key的缓存操作就会出现你这种情况

**Comment by z-chu** [comment]
我试了一下，开2个线程同时去对同一个key的缓存操作并不会有问题。
另外我说一下我对你遇到的情况的一些疑问。
1. 我不清楚你具体做了什么操作导致的该异常,是不是在缓存过程中对数据源做了其他操作。
2. 你缓存的数据源是什么?
3. 你用的缓存策略是什么?
如果你的工程源码可以公开，那你可以让我看看。

**Comment by findvoid** [comment]
我用的策略需要缓存情况onlyRemote  不需要缓存且有网情况:cacheAndRemote 不需要缓存且无网情况onlyCache,Android系统 7.1.1

**Comment by findvoid** [comment]
我稍微测试了一下应该是和系统版本有关系,6.0不会退出

**Comment by findvoid** [comment]
测试了一下只有7.0以上系统有崩溃的问题,但是有个问题,我用的策略是CacheStrategy.onlyRemote(),也会崩溃,逻辑上应该是不走cache,这个策略希望可以优化,或者添加一个只走网络请求不缓存的策略.
祝好!

**Comment by z-chu** [comment]
只走网络请求不缓存其实跟直接不使用rxcache一样， 你是想动态配置缓存策略吧

**Comment by z-chu** [comment]
可以，满足你

**Comment by z-chu** [comment]
只走网络请求不缓存的策略已经加上，CacheStrategy.none()，可以切换到v1分支查看。
至于7.0以上系统崩溃的问题，我还是不清楚是什么原因导致。
你可以fork我的工程，在sample中添加导致该错误的代码演示，给我看看

**Comment by z-chu** [comment]
你好，问题已经查明并解决，使用v1.2.5即可

**Comment by findvoid** [comment]
好的  我有机会试下  感谢
