### ISSUE TITLE
transformer 返回值

### ISSUE THREAD

**Issue by pingde** [z-chu/RxCache#7]
我用Rxjava用的是Flowable和consumer来做的，RxCache里面方法返回的ObservableTransformer用不了，有没有什么办法兼容一下，或者给个思路怎么来适配下

**Comment by z-chu** [comment]
使用v2版本即可，`compile 'com.zchu:rxcache:2.0.4'`

**Comment by z-chu** [comment]
抱歉看错了，现在我项目使用还是RxJava1.0,我抽时间看看你的这个问题

**Comment by z-chu** [comment]
大兄弟，你肯定有办法  (╭☞•́⍛•̀)╭☞ @shiweibsw

**Comment by z-chu** [comment]
最新代码已支持floawable，不过我还没发布到Jcenter

**Comment by z-chu** [comment]
v2.1.0已更新
