### ISSUE TITLE
怎么更好的支持多用户的缓存呢？

### ISSUE THREAD

**Issue by caprice** [z-chu/RxCache#8]
如题，求教：app有多用户切换登录的情况，针对同一个url的请求，返回结果是不一样的，用这个lib怎么支持呢，是key值加上userId后缀，还是缓存针对不同用户用不同的目录呢？

**Comment by z-chu** [comment]
给key值加上userId后缀和用不同目录都是可以支持的

**Comment by caprice** [comment]
多谢
