### ISSUE TITLE
demo中仅加载缓存(当缓存无数据时），还有先加载缓存后加在网络（第一次无缓存，无网络）这两种情况下，页面始终显示加载中，debug时onNext和onError均没有进入断点。

### ISSUE THREAD

**Issue by caprice** [z-chu/RxCache#9]
demo中仅加载缓存(当缓存无数据时），还有先加载缓存后加在网络（第一次无缓存，无网络）这两种情况下，页面始终显示加载中，debug时onNext和onError均没有进入断点。

**Comment by z-chu** [comment]
是这样没错，你用2.0版的话。因为RxJava2.0不能发出null值，你的以上2种情况使用的是  `Observable.empty()`。
如需定制，你可以继承`BaseStrategy` 或者去实现`IStrategy`。
另外RxCache还有`save`和`load`方法，返回的是`Observable`，你可以不使用`compose(rxCache.<~>transformer...))`方式，自由组合成你想要的策略

**Comment by caprice** [comment]
明白，看来是需要定制了。需求缓存策略是：先加载缓存数据到页面，再网络数据。用户第一次进入时，没网络，没缓存，再看网络请求是否成功。onError最终就要onError。当缓存有数据时，即使网络出现onError, 页面数据也还是应该显示缓存数据，顶多用toast提醒用户"网络错误"，这个看起来有些麻烦啊

**Comment by z-chu** [comment]
这确实是个问题，如果缓存没取到，网络onError了，最终就应该是要onError，而不是直Observable.empty(),不过你的这个需求在CacheAndRemotoStrategy的基础上修改很容易实现，我打算下个版本把这个问题解决。

**Comment by caprice** [comment]
![image](https://user-images.githubusercontent.com/2981114/29260773-96352c22-80fe-11e7-8d07-b191efc6acf0.png)
目前这样自己写一个就可以了，后面再参照你更好的做法。再一次感谢你的这个lib.

**Comment by z-chu** [comment]
已更新，已修复，使用v2.0.5版即可
